//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/New Input System/Input Actions Control.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputActionsControl : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputActionsControl()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Input Actions Control"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""ba235005-793f-46a0-a035-d49f5c9602bf"",
            ""actions"": [
                {
                    ""name"": ""SwitchLamp"",
                    ""type"": ""Button"",
                    ""id"": ""d86a9532-07f2-49e3-bfec-8570b11f4805"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""51f950b6-ca06-446b-a8c3-905f8f4b093c"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchLamp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_SwitchLamp = m_Player.FindAction("SwitchLamp", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_Player_SwitchLamp;
    public struct PlayerActions
    {
        private @InputActionsControl m_Wrapper;
        public PlayerActions(@InputActionsControl wrapper) { m_Wrapper = wrapper; }
        public InputAction @SwitchLamp => m_Wrapper.m_Player_SwitchLamp;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @SwitchLamp.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSwitchLamp;
                @SwitchLamp.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSwitchLamp;
                @SwitchLamp.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSwitchLamp;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @SwitchLamp.started += instance.OnSwitchLamp;
                @SwitchLamp.performed += instance.OnSwitchLamp;
                @SwitchLamp.canceled += instance.OnSwitchLamp;
            }
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    public interface IPlayerActions
    {
        void OnSwitchLamp(InputAction.CallbackContext context);
    }
}
